In [5]:
import pandas as pd

lab = pd.read_sas('/Users/konstantingeneralov/IDE/Data/BIOPRO_J.xpt.txt', format='xport', encoding='utf-8')
display(lab.head(), lab.info(), lab.describe(include='all'))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6401 entries, 0 to 6400
Data columns (total 41 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEQN      6401 non-null   float64
 1   LBXSATSI  5902 non-null   float64
 2   LBDSATLC  5902 non-null   float64
 3   LBXSAL    5905 non-null   float64
 4   LBDSALSI  5905 non-null   float64
 5   LBXSAPSI  5903 non-null   float64
 6   LBXSASSI  5882 non-null   float64
 7   LBXSC3SI  5901 non-null   float64
 8   LBXSBU    5901 non-null   float64
 9   LBDSBUSI  5901 non-null   float64
 10  LBXSCLSI  5904 non-null   float64
 11  LBXSCK    5899 non-null   float64
 12  LBXSCR    5903 non-null   float64
 13  LBDSCRSI  5903 non-null   float64
 14  LBXSGB    5901 non-null   float64
 15  LBDSGBSI  5901 non-null   float64
 16  LBXSGL    5901 non-null   float64
 17  LBDSGLSI  5901 non-null   float64
 18  LBXSGTSI  5902 non-null   float64
 19  LBDSGTLC  5902 non-null   float64
 20  LBXSIR    5902 non-null   float64
 21  LBDSIRSI  5902 non-null   float64
 22  LBXSLDSI  5773 non-null   float64
 23  LBXSOSSI  5901 non-null   float64
 24  LBXSPH    5901 non-null   float64
 25  LBDSPHSI  5901 non-null   float64
 26  LBXSKSI   5899 non-null   float64
 27  LBXSNASI  5904 non-null   float64
 28  LBXSTB    5903 non-null   float64
 29  LBDSTBSI  5902 non-null   float64
 30  LBDSTBLC  5903 non-null   float64
 31  LBXSCA    5901 non-null   float64
 32  LBDSCASI  5901 non-null   float64
 33  LBXSCH    5903 non-null   float64
 34  LBDSCHSI  5903 non-null   float64
 35  LBXSTP    5901 non-null   float64
 36  LBDSTPSI  5901 non-null   float64
 37  LBXSTR    5901 non-null   float64
 38  LBDSTRSI  5901 non-null   float64
 39  LBXSUA    5901 non-null   float64
 40  LBDSUASI  5901 non-null   float64
dtypes: float64(41)
memory usage: 2.0 MB

,SEQN,LBXSATSI,LBDSATLC,LBXSAL,LBDSALSI,LBXSAPSI,LBXSASSI,LBXSC3SI,LBXSBU,LBDSBUSI,...,LBXSCA,LBDSCASI,LBXSCH,LBDSCHSI,LBXSTP,LBDSTPSI,LBXSTR,LBDSTRSI,LBXSUA,LBDSUASI
0,93705.0,16.0,5.397605e-79,4.4,44.0,74.0,20.0,31.0,11.0,3.93,...,9.2,2.300,157.0,4.060,7.3,73.0,95.0,1.073,5.8,345.0
1,93706.0,10.0,5.397605e-79,4.4,44.0,79.0,14.0,28.0,12.0,4.28,...,9.6,2.400,149.0,3.853,7.1,71.0,92.0,1.039,8.0,475.8
2,93707.0,13.0,5.397605e-79,5.2,52.0,238.0,24.0,22.0,17.0,6.07,...,10.1,2.525,199.0,5.146,8.0,80.0,110.0,1.242,5.5,327.1
3,93708.0,19.0,5.397605e-79,3.9,39.0,66.0,21.0,27.0,16.0,5.71,...,9.5,2.375,210.0,5.431,7.1,71.0,72.0,0.813,4.5,267.7
4,93709.0,15.0,5.397605e-79,3.7,37.0,86.0,17.0,24.0,20.0,7.14,...,9.9,2.475,180.0,4.655,7.0,70.0,132.0,1.490,6.2,368.8

None

,SEQN,LBXSATSI,LBDSATLC,LBXSAL,LBDSALSI,LBXSAPSI,LBXSASSI,LBXSC3SI,LBXSBU,LBDSBUSI,...,LBXSCA,LBDSCASI,LBXSCH,LBDSCHSI,LBXSTP,LBDSTPSI,LBXSTR,LBDSTRSI,LBXSUA,LBDSUASI
count,6401.000000,5902.000000,5.902000e+03,5905.000000,5905.000000,5903.000000,5882.000000,5901.000000,5901.000000,5901.000000,...,5901.000000,5901.000000,5903.000000,5903.000000,5901.000000,5901.000000,5901.000000,5901.00000,5901.000000,5901.000000
mean,98293.354320,21.420197,1.694341e-04,4.078645,40.786452,90.616127,21.760456,25.541434,14.615489,5.218146,...,9.319793,2.329948,183.241741,4.738640,7.165819,71.658194,137.437553,1.55167,5.402406,321.335197
std,2685.012056,16.949439,1.301669e-02,0.345033,3.450328,52.392677,12.952607,2.481768,5.984281,2.136455,...,0.372979,0.093245,41.287669,1.067702,0.435356,4.353560,109.130574,1.23208,1.480927,88.085177
min,93705.000000,2.000000,5.397605e-79,2.100000,21.000000,16.000000,6.000000,16.000000,2.000000,0.710000,...,6.400000,1.600000,77.000000,1.991000,5.300000,53.000000,25.000000,0.28200,0.800000,47.600000
25%,95962.000000,12.000000,5.397605e-79,3.900000,39.000000,64.000000,16.000000,24.000000,11.000000,3.930000,...,9.100000,2.275000,153.000000,3.957000,6.900000,69.000000,77.000000,0.86900,4.300000,255.800000
50%,98284.000000,17.000000,5.397605e-79,4.100000,41.000000,79.000000,19.000000,26.000000,14.000000,5.000000,...,9.300000,2.325000,180.000000,4.655000,7.200000,72.000000,111.000000,1.25300,5.300000,315.200000
75%,100623.000000,25.000000,5.397605e-79,4.300000,43.000000,98.000000,23.000000,27.000000,17.000000,6.070000,...,9.600000,2.400000,208.000000,5.379000,7.400000,74.000000,162.000000,1.82900,6.300000,374.700000
max,102956.000000,420.000000,1.000000e+00,5.400000,54.000000,638.000000,272.000000,38.000000,79.000000,28.200000,...,11.700000,2.925000,438.000000,11.327000,10.000000,100.000000,2923.000000,33.00100,15.100000,898.100000

In [26]:
#death = pd.read_csv('/Users/konstantingeneralov/IDE/Data/NHANES_III_MORT_2019_PUBLIC.dat', sep="\t")
colspecs = [
    (0,5),   # SEQN
    (6,6),   # ELIGSTAT
    (7,7),   # MORTSTAT
    (8,11),  # MORTDODY
    (12,13), # MORTDODM
    (14,14), # MORTDODQ
    (15,18), # PERMTH_EXM
    (19,22), # PERMTH_INT
]

names = [
    "SEQN","ELIGSTAT","MORTSTAT","MORTDODY","MORTDODM","MORTDODQ","PERMTH_EXM","PERMTH_INT"
]

death = pd.read_fwf('/Users/konstantingeneralov/IDE/Data/NHIS_2018_MORT_2019_PUBLIC.dat', colspecs=colspecs, names=names)

display(death.head()); death.info(); display(death.describe(include='all'))

,SEQN,ELIGSTAT,MORTSTAT,MORTDODY,MORTDODM,MORTDODQ,PERMTH_EXM,PERMTH_INT
0,20180,NaN,NaN,10,0,NaN,0,...
1,20180,NaN,NaN,40,0,NaN,.,...
2,20180,NaN,NaN,60,0,NaN,0,...
3,20180,NaN,NaN,60,0,NaN,.,...
4,20180,NaN,NaN,80,0,NaN,0,...

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33686 entries, 0 to 33685
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SEQN        33686 non-null  int64
 1   ELIGSTAT    0 non-null      float64
 2   MORTSTAT    0 non-null      float64
 3   MORTDODY    33686 non-null  int64
 4   MORTDODM    33686 non-null  int64
 5   MORTDODQ    0 non-null      float64
 6   PERMTH_EXM  33686 non-null  object
 7   PERMTH_INT  33686 non-null  object
dtypes: float64(3), int64(3), object(2)
memory usage: 2.1+ MB

,SEQN,ELIGSTAT,MORTSTAT,MORTDODY,MORTDODM,MORTDODQ,PERMTH_EXM,PERMTH_INT
count,33686.0,0.0,0.0,33686.000000,33686.000000,0.0,33686,33686
unique,NaN,NaN,NaN,NaN,NaN,NaN,4,17
top,NaN,NaN,NaN,NaN,NaN,NaN,0,...
freq,NaN,NaN,NaN,NaN,NaN,NaN,24471,33235
mean,20180.0,NaN,NaN,495.714243,0.000178,NaN,NaN,NaN
std,0.0,NaN,NaN,288.557177,0.013345,NaN,NaN,NaN
min,20180.0,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN
25%,20180.0,NaN,NaN,250.000000,0.000000,NaN,NaN,NaN
50%,20180.0,NaN,NaN,490.000000,0.000000,NaN,NaN,NaN
75%,20180.0,NaN,NaN,750.000000,0.000000,NaN,NaN,NaN
max,20180.0,NaN,NaN,990.000000,1.000000,NaN,NaN,NaN