In [4]:
import pandas as pd     # Импорт библиотеки pandas для работы с табличными данными (DataFrame)
import numpy as np      # Импорт библиотеки numpy для работы с массивами и числовыми операциями
import seaborn as sns   # Импорт библиотеки seaborn для создания красивых и информативных визуализаций данных
from matplotlib import pyplot as plt              # Импорт функции pyplot из библиотеки matplotlib для создания графиков и визуализаций

from sklearn.preprocessing import OneHotEncoder, StandardScaler       # Импорт классов для кодирования категориальных признаков и стандартизации данных
from sklearn.model_selection import train_test_split   # Импорт функций для разбиения данных на тренировочную и тестовую выборки

from sklearn.linear_model import LogisticRegression   # Импорт модели логистической регрессии
from sklearn.neighbors import KNeighborsClassifier     # Импорт классификатора К-ближайших соседей
from sklearn.tree import DecisionTreeClassifier       # Импорт классификатора на основе дерева решений
from sklearn.svm import SVC                           # Импорт классификатора на основе метода опорных векторов (SVM)

from sklearn import metrics   # Импорт всего модуля metrics для работы с метриками оценки моделей
from sklearn.metrics import ( # Импорт конкретных функций оценки из подмодуля metrics
accuracy_score,            # Импорт функции для оценки точности (ассгасу) модели, т.е. доли правильно предсказанных примеров
balanced_accuracy_score,   # Импорт функции для оценки сбалансированной точности, учитывающей классовую неоднородность
precision_score,           # Импорт функции для вычисления точности (precision)
recall_score,              # Импорт функции для вычисления полноты (recall)
confusion_matrix,          # Импорт функции для создания матрицы ошибок (confusion matrix): TN, TP, FN, FP
multilabel_confusion_matrix, # Импорт функции для создания матрицы ошибок для случаев с многомерной классификацией
f1_score,                  # Импорт функции для вычисления F1-меры
roc_auc_score,             # Импорт функции для вычисления AUC-ROC (площадь под кривой приемлемости и ошибок)
roc_curve,                 # Импорт функции для вычисления координат для построения ROC-кривой
average_precision_score,   # Импорт функции для вычисления средней точности (average precision)
precision_recall_curve )   # Импорт функции для вычисления и визуализации кривой "точность-полнота" (precision-recall curve)


heart = pd.read_csv('/Users/konstantingeneralov/IDE/Data/heart_data.tsv', sep='\t')
heart_df = heart.copy()  # Создание копии DataFrame для дальнейшей работы
#дропнем столбец 'ID', так как он не несет полезной информации для анализа и моделирования
heart_df.drop(columns=['ID'], inplace=True)
display(heart_df.head(), heart_df.info(), heart_df.describe(include='all')) 


#Подсчитаем количество значений всех признаков датасета, включая пропущенные:


for col in heart_df.columns:
    print(f'Признак: {col}')
    print(heart_df[col].value_counts(dropna=False).to_string())

<class 'pandas.DataFrame'>
RangeIndex: 955 entries, 0 to 954
Data columns (total 37 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Пол                                     954 non-null    str
 1   Семья                                   955 non-null    str
 2   Этнос                                   955 non-null    str
 3   Национальность                          955 non-null    str
 4   Религия                                 955 non-null    str
 5   Образование                             955 non-null    str
 6   Профессия                               955 non-null    str
 7   Работа                                  955 non-null    int64
 8   Выход на пенсию                         955 non-null    int64
 9   Прекращение работы по болезни           955 non-null    int64
 10  Сахарный диабет                         955 non-null    int64
 11  Гепатит                                 955 non-null    int64
 12  Онкология                               955 non-null    int64
 13  Хроническое заболевание легких          955 non-null    int64
 14  Бронхиальная астма                      955 non-null    int64
 15  Туберкулез легких                       955 non-null    int64
 16  ВИЧ/СПИД                                955 non-null    int64
 17  Регулярный прием лекарственных средств  955 non-null    int64
 18  Травмы за год                           955 non-null    int64
 19  Переломы                                955 non-null    int64
 20  Статус Курения                          955 non-null    str
 21  Возраст курения                         412 non-null    float64
 22  Сигарет в день                          409 non-null    float64
 23  Пассивное курение                       955 non-null    int64
 24  Частота пасс кур                        223 non-null    str
 25  Алкоголь                                955 non-null    str
 26  Возраст алког                           788 non-null    float64
 27  Время засыпания                         955 non-null    str
 28  Время пробуждения                       955 non-null    str
 29  Сон после обеда                         955 non-null    int64
 30  Спорт, клубы                            955 non-null    int64
 31  Религия, клубы                          955 non-null    int64
 32  Артериальная гипертензия                955 non-null    int64
 33  ОНМК                                    955 non-null    int64
 34  Стенокардия, ИБС, инфаркт миокарда      955 non-null    int64
 35  Сердечная недостаточность               955 non-null    int64
 36  Прочие заболевания сердца               955 non-null    int64
dtypes: float64(3), int64(22), str(12)
memory usage: 276.2 KB

,Пол,Семья,Этнос,Национальность,Религия,Образование,Профессия,Работа,Выход на пенсию,Прекращение работы по болезни,...,Время засыпания,Время пробуждения,Сон после обеда,"Спорт, клубы","Религия, клубы",Артериальная гипертензия,ОНМК,"Стенокардия, ИБС, инфаркт миокарда",Сердечная недостаточность,Прочие заболевания сердца
0,М,в браке в настоящее время,европейская,Русские,Христианство,3 - средняя школа / закон.среднее / выше среднего,низкоквалифицированные работники,1,0,0,...,22:00:00,06:00:00,0,0,0,0,0,0,0,0
1,Ж,в разводе,европейская,Русские,Христианство,5 - ВУЗ,дипломированные специалисты,0,0,0,...,00:00:00,04:00:00,1,0,0,1,1,0,0,0
2,Ж,в браке в настоящее время,европейская,Русские,Христианство,5 - ВУЗ,дипломированные специалисты,0,0,0,...,23:00:00,07:00:00,0,0,0,0,0,0,0,0
3,М,в браке в настоящее время,европейская,Русские,Атеист / агностик,3 - средняя школа / закон.среднее / выше среднего,низкоквалифицированные работники,1,0,0,...,23:00:00,07:00:00,0,0,0,1,0,0,0,0
4,Ж,в браке в настоящее время,европейская,Русские,Христианство,3 - средняя школа / закон.среднее / выше среднего,операторы и монтажники установок и машинного о...,0,0,1,...,23:00:00,06:00:00,0,0,0,1,0,1,1,0

None

,Пол,Семья,Этнос,Национальность,Религия,Образование,Профессия,Работа,Выход на пенсию,Прекращение работы по болезни,...,Время засыпания,Время пробуждения,Сон после обеда,"Спорт, клубы","Религия, клубы",Артериальная гипертензия,ОНМК,"Стенокардия, ИБС, инфаркт миокарда",Сердечная недостаточность,Прочие заболевания сердца
count,954,955,955,955,955,955,955,955.000000,955.000000,955.000000,...,955,955,955.000000,955.000000,955.000000,955.000000,955.000000,955.000000,955.000000,955.000000
unique,2,6,3,18,4,4,11,NaN,NaN,NaN,...,22,34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,Ж,в браке в настоящее время,европейская,Русские,Христианство,4 - профессиональное училище,дипломированные специалисты,NaN,NaN,NaN,...,23:00:00,06:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,667,563,931,899,804,454,225,NaN,NaN,NaN,...,311,233,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.523560,0.335079,0.048168,...,NaN,NaN,0.226178,0.068063,0.023037,0.467016,0.042932,0.122513,0.100524,0.090052
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.499706,0.472265,0.214232,...,NaN,NaN,0.418575,0.251986,0.150098,0.499172,0.202810,0.328049,0.300854,0.286407
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,...,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,...,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.000000,0.000000,...,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,0.000000,...,NaN,NaN,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,1.000000,...,NaN,NaN,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

Признак: Пол
Пол
Ж      667
М      287
NaN      1
Признак: Семья
Семья
в браке в настоящее время                          563
вдовец / вдова                                     143
в разводе                                          125
гражданский брак / проживание с партнером           79
никогда не был(а) в браке                           43
раздельное проживание (официально не разведены)      2
Признак: Этнос
Этнос
европейская                                                                                                      931
другая азиатская (Корея, Малайзия, Таиланд, Вьетнам, Казахстан, Киргизия, Туркмения, Узбекистан, Таджикистан)     17
прочее (любая иная этно-расовая группа, не представленная выше)                                                    7
Признак: Национальность
Национальность
Русские                  899
Татары                    18
Немцы                      6
Чуваши                     5
Азербайджанцы              4
Украинцы                   4
Другие национальности      2
Мордва                     2
Киргизы                    2
Казахи                     2
Армяне                     2
Таджики                    2
Евреи                      2
Эстонцы                    1
Молдаване                  1
Белорусы                   1
Башкиры                    1
Буряты                     1
Признак: Религия
Религия
Христианство         804
Атеист / агностик     86
Нет                   41
Ислам                 24
Признак: Образование
Образование
4 - профессиональное училище                         454
5 - ВУЗ                                              313
3 - средняя школа / закон.среднее / выше среднего    181
2 - начальная школа                                    7
Признак: Профессия
Профессия
дипломированные специалисты                                                            225
низкоквалифицированные работники                                                       138
работники,  занятые в сфере обслуживания, торговые работники магазинов и рынков        123
служащие                                                                                90
ремесленники и представители других отраслей промышленности                             89
ведение домашнего хозяйства                                                             81
техники и младшие специалисты                                                           80
операторы и монтажники установок и машинного оборудования                               72
представители   законодат.   органов   власти,  высокопостав. долж.лица и менеджеры     35
квалифицированные работники сельского хозяйства и рыболовного                           17
вооруженные силы                                                                         5
Признак: Работа
Работа
1    500
0    455
Признак: Выход на пенсию
Выход на пенсию
0    635
1    320
Признак: Прекращение работы по болезни
Прекращение работы по болезни
0    909
1     46
Признак: Сахарный диабет
Сахарный диабет
0    854
1    101
Признак: Гепатит
Гепатит
0    840
1    115
Признак: Онкология
Онкология
0    912
1     43
Признак: Хроническое заболевание легких
Хроническое заболевание легких
0    883
1     72
Признак: Бронхиальная астма
Бронхиальная астма
0    914
1     41
Признак: Туберкулез легких
Туберкулез легких
0    935
1     20
Признак: ВИЧ/СПИД
ВИЧ/СПИД
0    953
1      2
Признак: Регулярный прием лекарственных средств
Регулярный прием лекарственных средств
1    614
0    341
Признак: Травмы за год
Травмы за год
0    904
1     51
Признак: Переломы
Переломы
0    617
1    338
Признак: Статус Курения
Статус Курения
Никогда не курил(а)    543
Курит                  221
Бросил(а)              191
Признак: Возраст курения
Возраст курения
NaN     543
20.0     71
18.0     61
17.0     45
16.0     38
15.0     23
25.0     17
19.0     17
30.0     13
12.0     10
14.0     10
21.0      9
24.0      9
35.0      8
7.0       8
22.0      8
23.0      8
40.0      6
13.0      6
10.0      5
6.0       4
8.0       3
26.0      3
45.0      3
27.0      3
39.0      2
29.0      2
36.0      2
28.0      2
54.0      1
5.0       1
53.0      1
37.0      1
58.0      1
34.0      1
51.0      1
41.0      1
33.0      1
47.0      1
11.0      1
50.0      1
32.0      1
42.0      1
52.0      1
55.0      1
Признак: Сигарет в день
Сигарет в день
NaN     546
20.0    116
10.0     83
5.0      36
15.0     28
30.0     18
1.0      17
40.0     16
3.0      15
2.0      15
4.0      15
6.0      11
12.0      9
7.0       8
8.0       7
60.0      3
25.0      3
13.0      2
17.0      2
35.0      1
50.0      1
18.0      1
14.0      1
16.0      1
Признак: Пассивное курение
Пассивное курение
0    731
1    224
Признак: Частота пасс кур
Частота пасс кур
NaN                       732
1-2 раза в неделю          92
4 и более раз в день       47
2-3 раза в день            30
не менее 1 раза в день     29
3-6 раз в неделю           25
Признак: Алкоголь
Алкоголь
употребляю в настоящее время    634
никогда не употреблял           165
ранее употреблял                156
Признак: Возраст алког
Возраст алког
20.0    183
NaN     167
18.0    160
17.0     91
16.0     66
25.0     57
19.0     42
21.0     36
15.0     29
22.0     21
30.0     17
23.0     15
14.0     10
35.0      8
12.0      5
24.0      5
26.0      5
40.0      4
27.0      4
29.0      4
13.0      3
37.0      3
32.0      2
10.0      2
6.0       2
50.0      2
33.0      2
28.0      2
48.0      1
9.0       1
46.0      1
45.0      1
36.0      1
63.0      1
43.0      1
44.0      1
Признак: Время засыпания
Время засыпания
23:00:00    311
00:00:00    213
22:00:00    165
01:00:00     65
23:30:00     45
22:30:00     41
21:00:00     39
02:00:00     22
00:30:00     20
21:30:00     12
01:30:00      5
23:59:00      5
02:30:00      2
03:00:00      2
01:20:00      1
20:30:00      1
00:01:00      1
00:15:00      1
12:00:00      1
20:00:00      1
23:50:00      1
22:23:00      1
Признак: Время пробуждения
Время пробуждения
06:00:00    233
07:00:00    222
08:00:00    136
06:30:00     72
09:00:00     67
05:30:00     51
07:30:00     37
05:00:00     37
10:00:00     27
04:00:00     15
08:30:00     15
04:30:00      6
12:00:00      4
09:30:00      4
06:20:00      3
11:00:00      3
06:15:00      3
03:00:00      2
07:20:00      2
06:40:00      2
04:40:00      1
06:03:00      1
05:20:00      1
06:50:00      1
10:30:00      1
03:30:00      1
05:50:00      1
05:40:00      1
06:45:00      1
07:08:00      1
08:03:00      1
00:00:00      1
06:05:00      1
07:15:00      1
Признак: Сон после обеда
Сон после обеда
0    739
1    216
Признак: Спорт, клубы
Спорт, клубы
0    890
1     65
Признак: Религия, клубы
Религия, клубы
0    933
1     22
Признак: Артериальная гипертензия
Артериальная гипертензия
0    509
1    446
Признак: ОНМК
ОНМК
0    914
1     41
Признак: Стенокардия, ИБС, инфаркт миокарда
Стенокардия, ИБС, инфаркт миокарда
0    838
1    117
Признак: Сердечная недостаточность
Сердечная недостаточность
0    859
1     96
Признак: Прочие заболевания сердца
Прочие заболевания сердца
0    869
1     86

In [39]:
# Кодирование категориальных признаков One-Hot методом

heart_df_3 = pd.read_csv('/Users/konstantingeneralov/IDE/Data/heart_data_cleaned.csv', sep=',')
heart_4 = heart_df_3.copy()  # Создание копии DataFrame для дальнейшей работы

columns_to_change = ['Семья', 'Этнос', 'Национальность', 'Религия', 'Профессия', 'Статус Курения', 'Алкоголь']
for column in columns_to_change:
 print('Число уникальных значений признака {}: '.format(column), heart_4[column].nunique())

# инициализация кодировщика OneHotEncoder
one_hot_encoder = OneHotEncoder()

# Обучаем энкодер, применяем преобразование к выборке. Результат переводим в массив
encoded_features = one_hot_encoder.fit_transform(heart_4[columns_to_change]).toarray()

# Сохраним полученные названия новых колонок в переменную colums
colums = one_hot_encoder.get_feature_names_out(columns_to_change)

# Преобразуем массив в формат DataFrame
encoded_df = pd.DataFrame(encoded_features, columns=colums)

# Переустановим индексацию в таблицах
# reset_index() — изменяет индексы с рандомных на последовательные от 0 до n
# drop(['index'], axis = 1) — удаляет образовавшийся столбец 'index'
encoded_df.reset_index(drop=True, inplace=True)
heart_4.reset_index(drop=True, inplace=True)   

# Объединим таблицы
heart_4 = pd.concat([heart_4, encoded_df], axis=1)

# Удалим старые категориальные признаки
heart_4.drop(columns=columns_to_change, inplace=True)

# Сделаем все признаки целочисленными
heart_4 = heart_4.astype(int)

summary = pd.DataFrame({
    "missing": heart_4.isnull().sum(),
    "unique": heart_4.nunique(),
    "dtype": heart_4.dtypes
})
display(summary)

heart_5 = heart_4.copy()  # Создание копии DataFrame для дальнейшей работы

# Удалим одну из коррелирующих переменных в каждой паре:
# Статус Курения_Никогда не курил(а)
# Алкоголь_никогда не употреблял
# Этнос_другая азиатская (Корея, Малайзия, Таиланд, Вьетнам, Казахстан, Киргизия, Туркмения, Узбекистан, Таджикистан)
heart_5.drop(columns=['Статус Курения_Никогда не курил(а)', 'Алкоголь_никогда не употреблял', 
                      'Этнос_другая азиатская (Корея, Малайзия, Таиланд, Вьетнам, Казахстан, Киргизия, Туркмения, Узбекистан, Таджикистан)'], inplace=True)

# сохраним конечный результат в новый файл
heart_5.to_csv('/Users/konstantingeneralov/IDE/Data/heart_data_final.csv', index=False)

# display(heart_5.head(), heart_5.info(), heart_5.describe(include='all'))

Число уникальных значений признака Семья:  6
Число уникальных значений признака Этнос:  3
Число уникальных значений признака Национальность:  18
Число уникальных значений признака Религия:  4
Число уникальных значений признака Профессия:  11
Число уникальных значений признака Статус Курения:  3
Число уникальных значений признака Алкоголь:  3

                                       missing  unique  dtype
Пол                                          0       2  int64
Образование                                  0       4  int64
Работа                                       0       2  int64
Выход на пенсию                              0       2  int64
Прекращение работы по болезни                0       2  int64
...                                        ...     ...    ...
Статус Курения_Курит                         0       2  int64
Статус Курения_Никогда не курил(а)           0       2  int64
Алкоголь_никогда не употреблял               0       2  int64
Алкоголь_ранее употреблял                    0       2  int64
Алкоголь_употребляю в настоящее время        0       2  int64

[76 rows x 3 columns]

In [43]:
#  Кодирование категориальных признаков по популярности

#display(heart_df_3.head(), heart_df_3.info(), heart_df_3.describe(include='all'))

heart_popularity = heart_df_3.copy()  # Создание копии DataFrame для дальнейшей работы

# Закодируем признаки по популярности с добавлением в закодированные значения небольшого уровня шума, чтобы различать категории с одинаковой популярностью

np.random.seed(42)
cats = ['Семья', 'Этнос', 'Национальность', 'Религия', 'Профессия', 'Статус Курения', 'Алкоголь']
for cat in cats:
    heart_popularity[cat] = heart_popularity[cat].map(heart_popularity[cat].value_counts()) + 0.1 * np.random.random(len(heart_popularity))

#Найдем сильно коррелирующие между собой признаки и удалим один из них в каждой паре, чтобы избежать мультиколлинеарности в модели
corr = heart_popularity.corr(numeric_only=True)
m = (corr.mask(np.eye(len(corr), dtype=bool)).abs() > 0.8).any()
raw = corr.loc[m, m]
raw

heart_popularity.drop(['Статус Курения'], axis=1, inplace=True)

# сохраним конечный результат в новый файл
heart_popularity.to_csv('/Users/konstantingeneralov/IDE/Data/heart_data_popularity.csv', index=False)

#display(heart_popularity.head(), heart_popularity.info(), heart_popularity.describe(include='all'))