In [8]:
# 1. Импорт библиотек

import numpy as np #для матричных вычислений
import pandas as pd #для анализа и предобработки данных
import matplotlib.pyplot as plt #для визуализации
import seaborn as sns #для визуализации
import torch # импортируем PyTorch
import torch.nn as nn #для создания нейронных сетей
import pytorch_lightning as pl

from sklearn import linear_model #линейные модели
from sklearn import metrics #метрики
from sklearn import preprocessing #предобработка
from sklearn.model_selection import train_test_split #разделение выборки
from sklearn import ensemble #ансамблевые методы

In [ ]:
# 2. Загрузка и анализ данных

train = pd.read_csv('/Users/konstantingeneralov/IDE/Data/DL_PJ_train.csv', sep=',')
test = pd.read_csv('/Users/konstantingeneralov/IDE/Data/DL_PJ_test.csv', sep=',')

df_train = train.copy()
df_test = test.copy()

display(df_train.head(), df_train.info(), df_train.describe())
display(df_test.head(), df_test.info(), df_test.describe())

# проверим кол-ва дубликатов в данных
duplicate_rows_train = df_train.duplicated().sum()
duplicate_rows_test = df_test.duplicated().sum()
print('Количество дубликатов в тренинговой выборке:', duplicate_rows_train)
print('Количество дубликатов в тестовой выборке:', duplicate_rows_test)

# проверим наличие пропущенных значений и уникальных значений в каждом столбце
summary = pd.DataFrame({
    "missing": df_train.isnull().sum(),
    "unique": df_train.nunique(),
    "dtype": df_train.dtypes
})
display('train',summary)

summary = pd.DataFrame({
    "missing": df_test.isnull().sum(),
    "unique": df_test.nunique(),
    "dtype": df_test.dtypes
})
display('test',summary)

<class 'pandas.DataFrame'>
RangeIndex: 600000 entries, 0 to 599999
Data columns (total 15 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   ID                                    600000 non-null  int64
 1   age                                   600000 non-null  float64
 2   sex                                   600000 non-null  int64
 3   chest                                 600000 non-null  float64
 4   resting_blood_pressure                600000 non-null  float64
 5   serum_cholestoral                     600000 non-null  float64
 6   fasting_blood_sugar                   600000 non-null  int64
 7   resting_electrocardiographic_results  600000 non-null  int64
 8   maximum_heart_rate_achieved           600000 non-null  float64
 9   exercise_induced_angina               600000 non-null  int64
 10  oldpeak                               600000 non-null  float64
 11  slope                                 600000 non-null  int64
 12  number_of_major_vessels               600000 non-null  int64
 13  thal                                  600000 non-null  int64
 14  class                                 600000 non-null  int64
dtypes: float64(6), int64(9)
memory usage: 68.7 MB

,ID,age,sex,chest,resting_blood_pressure,serum_cholestoral,fasting_blood_sugar,resting_electrocardiographic_results,maximum_heart_rate_achieved,exercise_induced_angina,oldpeak,slope,number_of_major_vessels,thal,class
0,0,49.207124,0,4.000000,162.996167,181.108682,0,0,148.227858,1,0.944547,2,0,3,1
1,1,53.628425,1,1.741596,130.233730,276.474630,0,2,152.917139,0,0.119070,2,0,3,0
2,2,49.591426,1,4.000000,146.999012,223.300517,1,2,102.352090,1,1.616747,2,2,7,1
3,3,58.991445,1,4.000000,112.369143,187.245501,0,0,158.164750,1,0.000000,1,1,7,1
4,4,51.053602,1,1.954609,138.032047,238.482868,0,0,172.540828,0,1.150464,1,1,3,0

None

,ID,age,sex,chest,resting_blood_pressure,serum_cholestoral,fasting_blood_sugar,resting_electrocardiographic_results,maximum_heart_rate_achieved,exercise_induced_angina,oldpeak,slope,number_of_major_vessels,thal,class
count,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000
mean,299999.500000,54.426085,0.677447,3.170247,131.340485,249.592420,0.150757,1.020148,149.592069,0.333502,1.051391,1.596033,0.681303,4.711378,0.444185
std,173205.225094,9.086041,0.467454,0.949618,17.842450,51.699976,0.357812,0.994204,23.072593,0.471464,1.144288,0.629821,0.950669,1.934766,0.496875
min,0.000000,26.061695,0.000000,-0.538498,82.918527,98.326263,0.000000,0.000000,61.844168,0.000000,-0.806788,1.000000,0.000000,3.000000,0.000000
25%,149999.750000,48.078493,0.000000,3.000000,119.924094,216.475964,0.000000,0.000000,135.704237,0.000000,0.000000,1.000000,0.000000,3.000000,0.000000
50%,299999.500000,55.133425,1.000000,3.000000,129.727941,244.233699,0.000000,2.000000,153.224828,0.000000,0.811101,2.000000,0.000000,3.000000,0.000000
75%,449999.250000,60.663775,1.000000,4.000000,139.915216,274.345453,0.000000,2.000000,165.165497,1.000000,1.674081,2.000000,1.000000,7.000000,1.000000
max,599999.000000,79.591647,1.000000,4.000000,209.673650,527.755764,1.000000,2.000000,208.735196,1.000000,6.803372,3.000000,3.000000,7.000000,1.000000

<class 'pandas.DataFrame'>
RangeIndex: 400000 entries, 0 to 399999
Data columns (total 14 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   ID                                    400000 non-null  int64
 1   age                                   400000 non-null  float64
 2   sex                                   400000 non-null  int64
 3   chest                                 400000 non-null  float64
 4   resting_blood_pressure                400000 non-null  float64
 5   serum_cholestoral                     400000 non-null  float64
 6   fasting_blood_sugar                   400000 non-null  int64
 7   resting_electrocardiographic_results  400000 non-null  int64
 8   maximum_heart_rate_achieved           400000 non-null  float64
 9   exercise_induced_angina               400000 non-null  int64
 10  oldpeak                               400000 non-null  float64
 11  slope                                 400000 non-null  int64
 12  number_of_major_vessels               400000 non-null  int64
 13  thal                                  400000 non-null  int64
dtypes: float64(6), int64(8)
memory usage: 42.7 MB

,ID,age,sex,chest,resting_blood_pressure,serum_cholestoral,fasting_blood_sugar,resting_electrocardiographic_results,maximum_heart_rate_achieved,exercise_induced_angina,oldpeak,slope,number_of_major_vessels,thal
0,600000,53.963191,1,4.000000,136.940829,236.862814,0,2,143.961525,1,0.711100,1,2,7
1,600001,49.621479,1,4.000000,122.024651,226.593019,0,2,112.220874,1,0.000000,1,1,7
2,600002,36.933893,1,1.300924,127.585643,351.061046,0,0,177.945922,0,0.313078,1,0,7
3,600003,54.884588,1,3.000000,124.876745,250.370530,0,0,153.176526,0,0.308277,1,1,7
4,600004,71.016392,0,1.746972,120.922600,210.979710,0,0,164.573122,0,1.021370,1,1,3

None

,ID,age,sex,chest,resting_blood_pressure,serum_cholestoral,fasting_blood_sugar,resting_electrocardiographic_results,maximum_heart_rate_achieved,exercise_induced_angina,oldpeak,slope,number_of_major_vessels,thal
count,400000.000000,400000.000000,400000.000000,400000.000000,400000.000000,400000.000000,400000.000000,400000.000000,400000.000000,400000.000000,400000.000000,400000.000000,400000.000000,400000.00000
mean,799999.500000,54.406917,0.676858,3.169252,131.369647,249.593475,0.151163,1.025295,149.659088,0.333085,1.050086,1.595072,0.681432,4.70715
std,115470.198175,9.101044,0.467677,0.950585,17.862279,51.720531,0.358208,0.994132,23.065911,0.471317,1.140986,0.628361,0.950323,1.93353
min,600000.000000,27.496874,0.000000,-0.337469,85.830892,94.958220,0.000000,0.000000,58.964662,0.000000,-0.601414,1.000000,0.000000,3.00000
25%,699999.750000,48.021226,0.000000,3.000000,119.942167,216.455450,0.000000,0.000000,135.818008,0.000000,0.000000,1.000000,0.000000,3.00000
50%,799999.500000,55.130138,1.000000,3.000000,129.735888,244.273212,0.000000,2.000000,153.337116,0.000000,0.816276,2.000000,0.000000,3.00000
75%,899999.250000,60.667833,1.000000,4.000000,139.935499,274.357993,0.000000,2.000000,165.216643,1.000000,1.671519,2.000000,1.000000,7.00000
max,999999.000000,80.751628,1.000000,4.000000,212.300808,527.712687,1.000000,2.000000,207.412021,1.000000,6.856219,3.000000,3.000000,7.00000

Количество дубликатов в тренинговой выборке: 0
Количество дубликатов в тестовой выборке: 0

'train'

                                      missing  unique    dtype
ID                                          0  600000    int64
age                                         0  594106  float64
sex                                         0       2    int64
chest                                       0  133009  float64
resting_blood_pressure                      0  596241  float64
serum_cholestoral                           0  598797  float64
fasting_blood_sugar                         0       2    int64
resting_electrocardiographic_results        0       3    int64
maximum_heart_rate_achieved                 0  597583  float64
exercise_induced_angina                     0       2    int64
oldpeak                                     0  384255  float64
slope                                       0       3    int64
number_of_major_vessels                     0       4    int64
thal                                        0       3    int64
class                                       0       2    int64

'test'

                                      missing  unique    dtype
ID                                          0  400000    int64
age                                         0  397391  float64
sex                                         0       2    int64
chest                                       0   90257  float64
resting_blood_pressure                      0  398274  float64
serum_cholestoral                           0  399436  float64
fasting_blood_sugar                         0       2    int64
resting_electrocardiographic_results        0       3    int64
maximum_heart_rate_achieved                 0  398888  float64
exercise_induced_angina                     0       2    int64
oldpeak                                     0  262462  float64
slope                                       0       3    int64
number_of_major_vessels                     0       4    int64
thal                                        0       3    int64

In [ ]:
# посмотрим выбросы